### ISSUE TITLE
CMakeLists.txt is invalid, there is no shared dir

### ISSUE THREAD

**Issue by JeremySant** [dilevin/computer-graphics-ray-casting#2]
When you try to `cmake ..` from `/build/` you get the output below as there is no dir named `shared`. This was a problem with the initial  `CMakeLists.txt` from A1 as well:

CMake Error at CMakeLists.txt:4 (include):
  include could not find load file:

   ~/shared/cmake/CMakeLists.txt

-- Configuring incomplete, errors occurred!

**Comment by dilevin** [comment]
Are you using the command exactly as specified in the readme ?

**Comment by dilevin** [comment]
git clone --recursive -b fix https://github.com/dilevin/computer-graphics-ray-casting.git

**Comment by JeremySant** [comment]
I did not sorry

**Comment by dilevin** [comment]
I’m going to leave this open in case other people have the same issue

**Comment by briluong** [comment]
I used the exact command specified above but am also getting that error when running cmake in the build folder

**Comment by dilevin** [comment]
I've made a couple of videos showing how to install this properly. InstallationA.mp4 shows my cutting and pasting the webpage command and successfully compiling the assignment. 

InstallationB.mp4 shows me cloning the repo incorrectly, manually changing to the branch with the fix and manually installing the shared submodule. 

They are available in the attached zip file.
[InstallVideos.zip](https://github.com/dilevin/computer-graphics-ray-casting/files/2771657/InstallVideos.zip)

**Comment by briluong** [comment]
Thank you for the videos! I should have clarified that the compilation works for the cloned repository, but there were errors when trying to compile the mirror repo I made following the steps in the link that was provided (https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private) *except using the command provided for cloning with --recursive -b fix instead of --bare. 

Pushing the mirror to the new repo did not copy over the contents of the shared folder for some reason... had to cp the files/folders from the cloned repo to the mirrored one but it build fine afterwards.
