### ISSUE TITLE
Correct output but... smaller / further away?

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-ray-casting#46]
Hi,

When I have the distance of my image plane set to "camera.d", I seem to get output that looks correct, but is too small / far away from the objects compared to the provided solution images. But if I use "camera.d - 1", then I seem to get exact matches to the solutions (so far at least).

[I originally thought we needed to use -camera.d since -w is the direction of our view, but then I just see no objects (except a plane when existent). So I assume the "d" value here is already some scaled -w. Please correct me if I'm wrong!]

What might be going on with the image plane distance and the "- 1" required to get matching output? Thank you!

**Comment by NPTP** [comment]
UPDATE: Okay, there's more to it. With the distance set to "camera.d", here's what my sphere-packing  id image looks like.

![image](https://user-images.githubusercontent.com/16977354/73093601-dfe75c00-3eac-11ea-8f11-381bc141d1be.png)

And here's what my sphere-and-plane normal image looks like (the one that's "too far away", where doing "- 1" makes it match the sample output exactly)

![image](https://user-images.githubusercontent.com/16977354/73093656-fbeafd80-3eac-11ea-9e4d-a2972ee089a8.png)

**Comment by darren-moore** [comment]
If you draw a picture, you'll see that smaller d should make the image smaller like zooming out with your camera.

> So I assume the "d" value here is already some scaled -w.

Recall that `d` is a scalar "distance" value so it doesn't make sense to consider it to be a scaled vector `-w` value.
![image](https://user-images.githubusercontent.com/16497418/73094824-643ade80-3eaf-11ea-8d5c-811fa198acc1.png)


I recommend you try to fix `sphere-and-plane` first since the camera is a bit simpler. Draw the scene on paper to figure out what the `ray` output of `viewing_ray` should look like, then debug from there. I bet there's an extra/missing vector operation in `viewing_ray`.

**Comment by NPTP** [comment]
Thanks for your help! I had to orient my pixel locations/image plane distance by using the correct orthonormal basis (since it changes for each json file) and scaling those differing u, v and w appropriately. Seems to work correctly now and makes perfect sense conceptually. Cheers.
