### ISSUE TITLE
Triangle soup working everywhere except normals

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-ray-casting#49]
Hi!
For depth and id, my triangle-soup renders look exactly the same as the solution images. However, for normals I get:

![image](https://user-images.githubusercontent.com/16977354/73111078-f7d3d580-3ed6-11ea-9a30-cb03ea6756eb.png)

I'm not sure what's going on, since the single triangle render spits out the right colour for the normal image, but here, all the triangles come out uniformly grey! I would try to debug, but in debug mode and not release mode, the render never finishes (waited 10+ mins with no results). Any ideas? Thanks!

**Comment by darren-moore** [comment]
https://github.com/dilevin/computer-graphics-ray-casting/issues/15 may help

**Comment by NPTP** [comment]
It looks like normalizing the normals fixed this one and now I get the right output. But if this doesn't change the direction of the normals, why is this necessary? And why only for the triangle soup and not the sole triangle, or the plane etc? (I got the right results from those without normalizing, although now I'm normalizing everything)

**Comment by darren-moore** [comment]
Good question. You're right that the essential part of the normal is the direction, not the length. It's necessary because of how the colour is computed in `main.cpp`. Since the space of colours is finite, but the possible lengths of vectors is infinite, you have to normalize it down at _some_ point if you want colour.

As for why plane and triangle look okay: See the `.json` data files and notice that plane normals are often already normalized. Similar with triangle I'd think: it happened that the triangle size gave a normalized result.

**Comment by NPTP** [comment]
Makes sense! Thank you for your previous help & answers here.

Helping us out on a Friday night is a blessing - you guys are truly awesome. Thanks again and have a great weekend.
