### ISSUE TITLE
Unsupported GCC version

### ISSUE THREAD

**Issue by allanrui96** [dilevin/computer-graphics-ray-casting#9]
I am having the following problem when running cmake on ECE UG machines. 
_#error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"_

The GCC version is gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by dilevin** [comment]
unfortunately the assignments are not officially supported on ECE lab machines since this is a CS course. There are two solutions:

1. Use the CS teaching laboratory machines. You should have access to the teaching lab since you are enrolled in a cs course. If not, contact support for help: https://www.teach.cs.toronto.edu/contact.html

2. Contact ECE systems administration to install an updated compiler. 

Solution 1. Is likely much easier.
